##**AMAAN JAVED SYED**
##**CODSOFT TASK-4 : SALES PREDICTION USING PYTHON**

In [ ]:
#importing the required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [ ]:
#importing the dataset
df=pd.read_csv('/content/drive/MyDrive/Datasets/advertising.csv')

In [ ]:
#displaying the top 5 values of the dataset
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [ ]:
#information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [ ]:
#statistical description of the dataset
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
#checking for null-values in dataset
df.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [ ]:
X=df.drop(['Sales'],axis=1)
y=df['Sales']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

##**LINEAR REGRESSION MODEL**

In [ ]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
#making predictions using Linear Regression Model
pred=model.predict(X_test)
pred

array([10.68909303,  8.67371102,  9.59969914, 24.99989846, 14.73590568,
        8.37604918, 10.70350416, 18.37670708,  9.9670026 , 17.87946837,
       23.52765543, 10.70692059, 13.37566958, 17.10051561, 11.77005197,
       13.31194616, 21.13395461,  9.10945664, 14.24009701, 18.86885012,
       25.00670623, 12.42508633, 16.61899482, 13.84289673,  7.80458355,
       15.13012055, 14.69687153, 20.70140682, 16.9844145 ,  8.94984434,
       12.59168427, 20.93257626, 21.34337227, 21.89151357,  7.23908022,
        7.06001103,  9.28335812, 15.6840471 , 13.33894748,  7.28903633,
       11.05676585,  9.08768206, 15.60592891, 18.21716827, 18.9560652 ,
       13.47385617,  5.36520991, 10.59696871, 15.66036131, 10.98229096,
       12.20805533, 20.70970272, 20.70533061, 16.95931925,  9.96622132,
        9.44413497, 23.60505449, 15.99066008, 18.06706692,  8.25675464])

In [ ]:
#checking for accuracy
r2=r2_score(y_test,pred)
r2

0.8692052734910128

##**RANDOM FOREST MODEL**

In [ ]:
rfr_model=RandomForestRegressor()
rfr_model.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
#predicting using Random Forest Model
rfr_pred=rfr_model.predict(X_test)

In [ ]:
rfr_pred

array([10.952, 10.415, 11.256, 25.172, 16.696, 11.54 ,  9.34 , 18.053,
        8.406, 18.103, 24.743, 11.367, 15.304, 18.842, 11.683, 12.65 ,
       20.381,  6.706, 13.968, 17.964, 25.194, 12.129, 17.315, 12.404,
       11.054, 14.458, 17.232, 22.354, 16.54 ,  7.771, 12.295, 23.231,
       20.276, 22.271,  6.348,  6.84 , 10.754, 17.304, 12.983,  7.179,
        9.701,  7.597, 14.362, 18.952, 18.252, 13.67 ,  5.44 , 10.422,
       14.737, 11.588, 11.808, 20.155, 20.237, 19.067, 10.364, 10.929,
       20.498, 17.872, 18.464,  6.393])

In [ ]:
#checking accuracy using Random Forest Model
rfr_r2=r2_score(y_test,rfr_pred)
rfr_r2

0.9222295464041875

##**DECISION TREE MODEL**

In [ ]:
dtr_model=DecisionTreeRegressor()
dtr_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
#making predictions using Decision Tree model
dtr_pred=dtr_model.predict(X_test)
dtr_pred

array([10.9,  9.7, 13.2, 25.5, 16.7, 12.6, 12. , 18.4,  6.6, 17.4, 25.4,
       11. , 15.6, 19.7, 11.3, 11.5, 20.9,  9.5, 12.6, 17.4, 25.5, 14. ,
       17.5, 11.9,  9.4, 17.3, 17.1, 22.3, 16.5,  7.3, 12.6, 23.8, 19.8,
       22.2,  7. ,  6.6,  9.7, 17.5, 12. ,  6.6,  6.6,  5.7, 14.2, 20.2,
       18. , 14.2,  3.2, 12. , 17.2, 10.6, 12.2, 20.8, 18.9, 19.7,  9.6,
        9.7, 19.8, 17.5, 17.4,  7.3])

In [ ]:
#checking accuracy using Decision Tree Model
dtr_r2=r2_score(y_test,dtr_pred)
dtr_r2

0.8604485224712846